In [15]:
import numpy as n

In [29]:
arr1=n.array([10,20,30,4,0,50])
print(arr1)

[10 20 30  4  0 50]


In [120]:
arr2=n.array([[1,2,3,4,5,6,7,8,9],[9,8,7,4,5,6,4,5,12]])
print(arr2)

[[ 1  2  3  4  5  6  7  8  9]
 [ 9  8  7  4  5  6  4  5 12]]


In [28]:
data=[
    [
        [1,2,3,4],
        [2,3,4,5],
        [3,4,5,6]
    ],
    [
        [7,8,9,10],
        [8,9,4,5],
        [5,8,7,4],
    ],
    [
        [7,8,9,10],
        [8,9,4,5],
        [5,8,7,4],
    ]
    
]
print(n.array(data))

[[[ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]]

 [[ 7  8  9 10]
  [ 8  9  4  5]
  [ 5  8  7  4]]

 [[ 7  8  9 10]
  [ 8  9  4  5]
  [ 5  8  7  4]]]


In [35]:
arr01=n.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
arr02=n.zeros((10,20))
print(arr02)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [45]:
arr03=n.zeros((2,10,20))
print(arr03)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [47]:
arr11=n.ones(10)
print(arr11)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [53]:
arr12=n.ones((3,5))
print(arr12)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
arr13=n.ones((2,3,4))
print(arr13)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [60]:
arre=n.eye(3)
print(arre)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [85]:
arrR=n.random.randint(1,7,size=(2,3))
print(arrR)

[[3 4 1]
 [6 4 5]]


In [100]:
ar1=n.random.randint(1,7,size=5)
print(ar1)

[5 2 3 4 4]


In [103]:
ar1.resize(2)
print(ar1)

[5 2]


In [121]:
print(ar1.dtype)

int32


In [123]:
print(ar1.size)

2


In [133]:
array1=n.array([[1,2,3],[4,5,6]])
array2=n.array([[7,8,9],[10,11,12]])
print(n.hstack(array1))
print(n.hstack((array1,array2)))

[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [136]:
array1 = n.array([[1, 2], [3, 4]])
array2 = n.array([[5, 6], [7, 8]])
result = n.vstack((array1, array2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
